"""Fetching a paper's text from arXiv's LaTeXML renderings.

Two sources emit the same DOM, so one converter serves both: arXiv's own
native HTML5 rendering first because it is authoritative, then ar5iv because
its historical backfill is broader. A paper with neither is reported
unavailable rather than raising - the identifier is already in hand and the
bibliography is already recorded, so a missing body is a smaller loss than a
refused add.
"""

from __future__ import annotations

import httpx
import pytest

from kennis.engine.literature.fetch import PaperText, convert_arxiv_html, fetch_paper

LATEXML = """<html><body>
<header class="ltx_page_header">Report an issue</header>
<article class="ltx_document">
  <h1 class="ltx_title">Revisiting the Measurement Equation</h1>
  <p>The visibility <math alttext="V_{pq}" display="inline">MATHML</math> is
  measured.</p>
  <math alttext="\\int_0^1 x\\,dx" display="block">MATHML</math>
  <p>See <a href="../other.html">the other page</a> and
  <img src="images/fig1.png" alt="figure"/>.</p>
  <script>ignore()</script>
</article>
<footer class="ltx_page_footer">Generated by LaTeXML</footer>
</body></html>
"""

NOT_LATEXML = "<html><body><p>Just a moment, checking your browser.</p></body></html>"

PAGE_URL = "https://arxiv.org/html/1101.1764"


def routed(responses: dict[str, httpx.Response]) -> httpx.Client:
    """A client answering by exact host, so the two sources can differ.

    Matching on a URL substring would not work here: `ar5iv.labs.arxiv.org`
    contains `arxiv.org`, so the fallback would answer to the rule written
    for the source it is a fallback for.
    """

    def handler(request: httpx.Request) -> httpx.Response:
        return responses.get(request.url.host, httpx.Response(404))

    return httpx.Client(transport=httpx.MockTransport(handler))


def html(body: str) -> httpx.Response:
    """A 200 that says it is HTML, as a real host does.

    The content type is not decoration here: a source answering with XML is
    refused rather than parsed, so a fixture that omits it is testing the
    refusal instead of the fetch.
    """
    return httpx.Response(200, text=body, headers={"content-type": "text/html"})


# ---------------------------------------------------------------------------
# Choosing a source
# ---------------------------------------------------------------------------


def test_arxiv_native_html_is_tried_first():
    client = routed(
        {
            "arxiv.org": html(LATEXML),
            "ar5iv.labs.arxiv.org": html(LATEXML),
        }
    )
    result = fetch_paper("1101.1764", client=client)

    assert result.source == "arxiv-html"
    assert result.page_url == PAGE_URL


def test_ar5iv_is_the_fallback_when_arxiv_has_not_rendered_it():
    """A 404 is the expected 'not rendered at this source' answer, not a
    failure: arXiv backfills its own HTML and ar5iv started earlier."""
    client = routed(
        {
            "arxiv.org": httpx.Response(404),
            "ar5iv.labs.arxiv.org": html(LATEXML),
        }
    )
    result = fetch_paper("1101.1764", client=client)

    assert result.source == "ar5iv"
    assert result.markdown is not None


def test_a_paper_neither_source_renders_is_unavailable_not_an_error():
    """A 404 from both is the ordinary case - the paper was never rendered -
    so it reports an absence and not a refusal."""
    result = fetch_paper("1101.1764", client=routed({}))

    assert result == PaperText(
        markdown=None,
        source="unavailable",
        page_url=None,
        reason="neither source has rendered it",
    )


def test_a_network_failure_is_unavailable_too():
    def handler(request: httpx.Request) -> httpx.Response:
        raise httpx.ConnectError("no route to host")

    client = httpx.Client(transport=httpx.MockTransport(handler))
    assert fetch_paper("1101.1764", client=client).source == "unavailable"


def test_a_page_without_the_article_container_is_not_accepted():
    """Status 200 is not evidence that the fetch got the paper: a challenge
    page is served as 200 with an HTML body. What distinguishes it is that it
    has no LaTeXML article in it."""
    client = routed(
        {
            "arxiv.org": html(NOT_LATEXML),
            "ar5iv.labs.arxiv.org": html(NOT_LATEXML),
        }
    )
    result = fetch_paper("1101.1764", client=client)

    assert result.source == "unavailable"
    assert result.markdown is None


# ---------------------------------------------------------------------------
# Converting the article
# ---------------------------------------------------------------------------


def test_equations_are_kept_as_their_original_latex():
    """Every LaTeXML `math` element carries its LaTeX source in `alttext`, so
    the equation survives without parsing the MathML underneath."""
    markdown = convert_arxiv_html(LATEXML, PAGE_URL)

    assert "$V_{pq}$" in markdown
    assert "$$\\int_0^1 x\\,dx$$" in markdown
    assert "MATHML" not in markdown


def test_page_furniture_is_dropped():
    markdown = convert_arxiv_html(LATEXML, PAGE_URL)

    assert "Report an issue" not in markdown
    assert "Generated by LaTeXML" not in markdown
    assert "ignore()" not in markdown
    assert "Revisiting the Measurement Equation" in markdown


def test_links_and_images_are_resolved_against_the_page():
    """The markdown leaves the site it came from, so a relative reference in
    it would point at nothing."""
    markdown = convert_arxiv_html(LATEXML, PAGE_URL)

    assert "https://arxiv.org/other.html" in markdown
    assert "https://arxiv.org/html/images/fig1.png" in markdown


def test_a_document_with_no_article_container_is_refused():
    from kennis.engine.errors import SourceUnreadable

    with pytest.raises(SourceUnreadable):
        convert_arxiv_html(NOT_LATEXML, PAGE_URL)


# ---------------------------------------------------------------------------
# Saying why there is no text
# ---------------------------------------------------------------------------


def test_a_refusal_is_reported_rather_than_read_as_an_absence():
    """arXiv answers a burst with 406, from an address-level throttle whose
    window is minutes. The stub written is identical to the one written for a
    paper nobody preprinted, and the remedy is not, so the two must not come
    back as the same answer."""
    client = routed(
        {
            "arxiv.org": httpx.Response(406),
            "ar5iv.labs.arxiv.org": httpx.Response(406),
        }
    )
    result = fetch_paper("1101.1764", client=client)

    assert result.source == "unavailable"
    assert result.reason is not None
    assert "406" in result.reason
    assert "arxiv-html" in result.reason and "ar5iv" in result.reason


def test_an_unreachable_source_says_so():
    def handler(request: httpx.Request) -> httpx.Response:
        raise httpx.ConnectError("no route to host")

    result = fetch_paper(
        "1101.1764", client=httpx.Client(transport=httpx.MockTransport(handler))
    )

    assert result.reason is not None
    assert "could not be reached" in result.reason
