"""Writing the `generated:` block. Design section 3.

**One property decides the whole design**: a rebuild that altered nothing
must leave the file byte-identical, because the pack file's sha256 is the
fast path in section 5 step 2, and a provider that calls `pack update` on
every release would otherwise change that hash every time and defeat it.

Two consequences follow, and the second is the one that shapes the code.

**When nothing changed, nothing is written.** Not rewritten with the same
bytes - not opened for writing at all. Stronger than the design asks for,
and much easier to be certain of.

**When something changed, only the block is rewritten.** Dumping the parsed
`Pack` back through `yaml.dump` would produce a valid file that had lost the
editor header line `pack init` exists to write, every comment an author put
there, and whatever key order they chose. So the rewrite is textual: the
generated block is the **trailing section**, and `update` replaces from its
anchor to the end of the file. Everything above is untouched bytes.

That makes "the generated block is last" a rule of the format rather than a
habit of the example in section 7, where it is already last. An author who
moves their own content below it would have that content replaced, so a
block that is not the last section is refused rather than truncated.
"""

from __future__ import annotations

import time
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Final, Literal

import yaml

from kennis import __version__
from kennis.engine.errors import PackInvalid
from kennis.engine.events import EventSink, ItemFinished, OperationFinished, Outcome
from kennis.engine.pack.content import SourceContent, address_of, read_source
from kennis.engine.pack.schema import (
    ContentSource,
    GeneratedContent,
    GeneratedSource,
    Pack,
    load_pack,
)
from kennis.engine.pack.validate import version_refusal

GENERATED_MARKER: Final = "# Generated by `kennis pack update` - do not hand-edit."

OPERATION: Final = "pack-update"

_GENERATED_KEY: Final = "generated:"


@dataclass(frozen=True, slots=True)
class PackUpdate:
    """What `pack update` did, and to how much."""

    path: Path
    outcome: Literal["written", "unchanged"]
    files: int
    # Files sitting in a declared source that no `include` pattern matched.
    # Counted rather than dropped, because the default `**/*.md` silently
    # discarding a PDF an author meant to ship is the shape of mistake
    # nothing else here would catch. Concern #266.
    unselected: int


def update_pack(path: Path, *, events: EventSink | None = None) -> PackUpdate:
    """Recompute the generated block of the pack at `path`.

    Raises `PackInvalid` when the file does not parse, when this kennis may
    not read it, when a declared source is not a directory, when a file
    under one escapes the pack root, or when the generated block is not the
    last section.

    **`update` refuses where `validate` reports.** A missing source is a
    finding in a report and a refusal in a rewrite: writing an empty digest
    map is indistinguishable from a pack that ships nothing, and section 5
    step 2 treats that claim as authority to delete the user's files.

    **`events` is where this operation has most to say.** The report is one
    line - "2 files recorded" - and the log is the only place that records
    *which* two, and which of them are new, changed or gone since the last
    block. Section 14: the log holds what the report leaves out.
    """
    started = time.monotonic()
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as error:
        raise PackInvalid(f"{path} could not be read: {error}") from error
    pack = load_pack(text)

    refusal = version_refusal(pack)
    if refusal is not None:
        # A newer schema may nest content differently, so a block written in
        # this kennis's shape would corrupt a file it was told not to read.
        raise PackInvalid(
            f"this pack needs {refusal.kind.replace('-', ' ')} "
            f"({refusal.required}, this is {refusal.available}), "
            "so its generated block has been left alone",
            resolution="uv tool upgrade kennis",
        )

    content, unselected = _walked(path.parent, pack)
    previous = pack.generated.content if pack.generated is not None else None
    _reported(events, previous, content, unselected, started)
    if previous is not None and previous == content:
        return PackUpdate(
            path=path,
            outcome="unchanged",
            files=_counted(content),
            unselected=len(unselected),
        )

    path.write_text(_spliced(text, content), encoding="utf-8")
    return PackUpdate(
        path=path,
        outcome="written",
        files=_counted(content),
        unselected=len(unselected),
    )


def _reported(
    events: EventSink | None,
    previous: GeneratedContent | None,
    current: GeneratedContent,
    unselected: list[str],
    started: float,
) -> None:
    """Every shipped file to the stream, with what happened to its digest."""
    if events is None:
        return
    for address in sorted(unselected):
        events.emit(
            ItemFinished(
                operation=OPERATION,
                item=address,
                outcome=Outcome.SKIPPED,
                reason="no include pattern matches it",
            )
        )
    was = _flattened(previous) if previous is not None else {}
    now = _flattened(current)
    counts: dict[Outcome, int] = (
        {Outcome.SKIPPED: len(unselected)} if unselected else {}
    )
    for address in sorted(set(was) | set(now)):
        outcome = _outcome_for(address, was, now)
        counts[outcome] = counts.get(outcome, 0) + 1
        events.emit(ItemFinished(operation=OPERATION, item=address, outcome=outcome))
    events.emit(
        OperationFinished(
            operation=OPERATION,
            elapsed_seconds=time.monotonic() - started,
            counts=counts,
        )
    )


def _outcome_for(address: str, was: dict[str, str], now: dict[str, str]) -> Outcome:
    if address not in was:
        return Outcome.ADDED
    if address not in now:
        return Outcome.REMOVED
    return Outcome.UNCHANGED if was[address] == now[address] else Outcome.CHANGED


def _flattened(content: GeneratedContent) -> dict[str, str]:
    """Every digest keyed by `section:path`, which is what identifies it.

    **Not by path alone.** A pack may ship one tree to `notes` and to
    `context` - `validate` allows it, because section 5's diff key carries
    the section and the two destinations are distinct - so keying on the
    path would collapse two items into one and under-report the change.
    Flattened only for reporting; the block stays nested.
    """
    return {
        f"{section}:{address_of(entry.source, relative)}": digest
        for section, entries in (("notes", content.notes), ("context", content.context))
        for entry in entries
        for relative, digest in entry.files.items()
    }


def _walked(root: Path, pack: Pack) -> tuple[GeneratedContent, list[str]]:
    """Every declared source read, with the files no pattern took.

    Refuses anything that is not shippable on the way through: a missing
    directory, or a file that escapes the pack root.
    """
    unselected: list[str] = []
    notes = [_entry(root, source, unselected) for source in pack.corpus.notes]
    context = [_entry(root, source, unselected) for source in pack.context]
    return GeneratedContent(notes=notes, context=context), unselected


def _entry(root: Path, source: ContentSource, unselected: list[str]) -> GeneratedSource:
    found = read_source(root, source)
    _refuse_unshippable(found)
    unselected.extend(found.unselected)
    return GeneratedSource(source=source.source, files=found.digests)


def _refuse_unshippable(found: SourceContent) -> None:
    """The two states a pack may not be published in."""
    if not found.exists:
        raise PackInvalid(
            f"{found.source} is declared and is not a directory in the pack",
            resolution=None,
        )
    if found.escaping:
        named = ", ".join(found.escaping)
        raise PackInvalid(
            f"{named} resolves outside the pack, and a digest for it would "
            "be a claim about a file the pack does not own",
            resolution=None,
        )


def _counted(content: GeneratedContent) -> int:
    return sum(len(entry.files) for entry in [*content.notes, *content.context])


def _spliced(text: str, content: GeneratedContent) -> str:
    """The file with its generated block replaced, or gaining one."""
    anchor = _anchor(text)
    head = text if anchor is None else text[:anchor]
    return head.rstrip("\n") + "\n\n" + _rendered(content)


def _anchor(text: str) -> int | None:
    """Where the generated block starts, or None when there is not one.

    The marker if it is there, and otherwise a top-level `generated:` line -
    so a block a provider wrote by hand is rewritten rather than duplicated.
    Whichever it is, everything after it must be the block and nothing else.
    """
    found = _sole_index(text, GENERATED_MARKER)
    if found is None:
        found = _sole_index(text, f"\n{_GENERATED_KEY}")
        if found is not None:
            found += 1
    if found is None:
        return None
    _refuse_trailing_content(text[found:])
    return found


def _sole_index(text: str, needle: str) -> int | None:
    """The index of `needle`, refusing a file that holds it twice."""
    count = text.count(needle)
    if count == 0:
        return None
    if count > 1:
        raise PackInvalid(
            f"this file holds `{needle.strip()}` {count} times, and the "
            "generated block is written once at the end",
            resolution=None,
        )
    return text.index(needle)


def _refuse_trailing_content(tail: str) -> None:
    """Refuse when anything but the block sits below the anchor.

    The rewrite replaces from the anchor to the end of the file, so an
    author who moved their own declarations below it would lose them.
    Checked by parsing the tail rather than by scanning for keys, because
    YAML's ways of opening a mapping are more numerous than a scan would
    cover.
    """
    try:
        document = yaml.safe_load(tail)
    except yaml.YAMLError as error:
        raise PackInvalid(
            f"the generated block does not parse on its own: {error}",
            resolution=None,
        ) from error
    if document is None:
        return
    if not isinstance(document, dict) or set(document) != {"generated"}:
        found = ", ".join(sorted(document)) if isinstance(document, dict) else "content"
        raise PackInvalid(
            f"the generated block is not the last section: {found} follows "
            "it, and rewriting the block would replace it",
            resolution=None,
        )


def _rendered(content: GeneratedContent) -> str:
    """The block as text, in the shape design section 7 shows.

    Written out rather than dumped so the marker, the key order and the
    quoting are the ones a reader of the design recognises.
    """
    stamped = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        GENERATED_MARKER,
        "generated:",
        f'  at: "{stamped}"',
        # major.minor.patch of the kennis that wrote the digests. Section 5
        # step 2 compares its major.minor against the running kennis to
        # decide whether materialisation has changed since.
        f'  by: "kennis {__version__}"',
    ]
    sections = [
        (name, entries)
        for name, entries in (("context", content.context), ("notes", content.notes))
        if entries
    ]
    if not sections:
        lines.append("  content: {}")
        return "\n".join(lines) + "\n"
    lines.append("  content:")
    for name, entries in sections:
        lines.append(f"    {name}:")
        for entry in entries:
            lines.append(f"      - source: {entry.source}")
            if not entry.files:
                lines.append("        files: {}")
                continue
            lines.append("        files:")
            for relative, digest in sorted(entry.files.items()):
                lines.append(f'          "{relative}": "{digest}"')
    return "\n".join(lines) + "\n"


__all__ = ["GENERATED_MARKER", "OPERATION", "PackUpdate", "update_pack"]
