"""Render the settings reference table from the pydantic model.

The table in `docs/reference/configuration.md` is the model's own field
names, types, defaults and descriptions. Transcribing them would produce a
page that is correct on the day it is written and wrong on the day a default
changes, and nothing would say so - a stale reference is worse than a
missing one, because a reader believes it.

So the table is generated into a partial and included, and
`tests/test_docs.py` fails when the committed partial and the model
disagree. Run with `uv run scripts/generate_settings_table.py`.
"""

from __future__ import annotations

import typing
from pathlib import Path

from pydantic import BaseModel
from pydantic.fields import FieldInfo

from kennis.engine.settings import Settings

PARTIAL = Path("docs/reference/_settings-table.md")

_BANNER = (
    "<!-- Generated by scripts/generate_settings_table.py. Do not edit: a\n"
    "     test compares this file against the model and fails on drift. -->\n"
)


def _type_of(field: FieldInfo) -> str:
    """The field's type, with a Literal spelled out as its choices."""
    name = getattr(field.annotation, "__name__", str(field.annotation))
    if name != "Literal":
        return f"`{name}`"
    return " / ".join(f"`{choice}`" for choice in typing.get_args(field.annotation))


def _default_of(field: FieldInfo) -> str:
    return '`""`' if field.default == "" else f"`{field.default}`"


def render() -> str:
    lines = [_BANNER]
    for section, field in Settings.model_fields.items():
        model = field.annotation
        if not (isinstance(model, type) and issubclass(model, BaseModel)):
            continue
        summary = (model.__doc__ or "").strip().split("\n")[0]
        lines.append(f"### `[{section}]`\n")
        if summary:
            lines.append(f"{summary}\n")
        lines.append("| key | type | default | what it does |")
        lines.append("|---|---|---|---|")
        for key, sub in model.model_fields.items():
            # A pipe in a description would end the cell early.
            description = (sub.description or "").replace("|", "/").strip()
            lines.append(
                f"| `{key}` | {_type_of(sub)} | {_default_of(sub)} | {description} |"
            )
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    PARTIAL.write_text(render())
    print(f"wrote {PARTIAL}")


if __name__ == "__main__":
    main()
